version: '3'
services:

  # kanban-postgres:
  #   image: "postgres:9.6-alpine"
  #   container_name: kanban-postgres
  #   volumes:
  #     - kanban-data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_DB:kanban
  #     - POSTGRES_USER:kanban
  #     - POSTGRES_PASSWORD:kanban

  dev-istsos-proxy:
    build:
      dockerfile: dev.Dockerfile
      context: ./istsos
    container_name: dev-istsos
    volumes:
      - ./istsos:/home/py4web/apps/istsos
    # environment:
    #   - DB_SERVER=kanban-postgres
    ports:
      - 8000:8000

    # links:
    #   - kanban-postgres

  dev-simile-gui:
    build:
      context: ./simile
      dockerfile: dev.Dockerfile
    container_name: dev-simile
    ports:
      - 8080:8080
    # links:
    #   - kanban-app
    volumes:
      - ./simile:/usr/src/app/
      # - /usr/src/app/node_modules
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    command: npm run dev



# volumes:
#   kanban-data:
